version: '3'
services:
  backend:
    build: .
#    image: adaclosure/acmw-backend-next
    ports:
      - "8080:8080"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: accountant_meow
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
