server:
  port: 8080

spring:
  security:
    user:
      name: ${USER_NAME}
      password: ${USER_PSWD}
  datasource:
    username: ${DB_USER_NAME}
    password: ${DB_USER_PSWD}
    url: jdbc:postgresql://${DB_URL}:5432/accountant_meow?serverTimezone=PRC
    driver-class-name: org.postgresql.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms
  flyway:
    enabled: true
    encoding: UTF-8
    # 可以支持多个location, 用','隔开
    locations: classpath:db/migration
    # migrate是否校验
    validate-on-migrate: true

#整合MyBatis
mybatis:
  #  mapper.xml的目录
  mapper-locations: classpath:mapper/*Mapper.xml
  #  实体类的目录
  type-aliases-package: com.meow.accountant.entity
