// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/files"

const swaggerInfo = `{
    "swagger": "2.0",
    "info": {
        "title": "Accountant Meow Backend API",
        "description": "记账喵后端 API 文档",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Support",
            "url": "https://github.com/lingluo-hub/accountant-meow-backend"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "2.0.0"
    },
    "host": "localhost:8080",
    "basePath": "/api/v1",
    "paths": {
        "/public/health": {
            "get": {
                "description": "Check if the service is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "ok"
                                },
                                "version": {
                                    "type": "string",
                                    "example": "2.0.0"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}
`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

func init() {
	SwaggerInfo.Version = "2.0.0"
	SwaggerInfo.Host = "localhost:8080"
	SwaggerInfo.BasePath = "/api/v1"
	SwaggerInfo.Schemes = []string{}
	SwaggerInfo.Title = "Accountant Meow Backend API"
	SwaggerInfo.Description = "记账喵后端 API 文档"
}

type s struct{}

func (s s) ReadDoc() string {
	return swaggerInfo
}

func init() {
	files.SwaggerInfo = s{}
}
